version: '2'
services:
  cli:
    build:
      context: services/cli
      args:
        - USER
    stdin_open: true
    tty: true
    volumes:
       - ./workdir:/home/${USER}/workdir
  ubuntu-focal:
    build:
      context: services/ubuntu-focal
      args:
        - USER
    stdin_open: true
    tty: true
    volumes:
       - ./workdir:/home/${USER}/workdir
