version: '2'
services:
  cli:
    build:
      context: services
      dockerfile: cli/Dockerfile
      args:
        - USER
    stdin_open: true
    tty: true
    volumes:
       - ./workdir:/home/${USER}/workdir
  ubuntu-focal:
    build:
      context: services
      dockerfile: ubuntu-focal/Dockerfile
      args:
        - USER
    stdin_open: true
    tty: true
    volumes:
       - ./workdir:/home/${USER}/workdir
